In [12]:
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 15 18:30:50 2022
@credits: https://github.com/vishwamano/Artificial-Neural-Networks--ANN-/blob/main/artificial_neural_network.py
"""
import numpy as np
import pandas as pd
import tensorflow as tf

#check tensorflow version
tf.__version__

#Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

#loda the data in variable X, leave the first 3 columns
X = dataset.iloc[:, 3:-1].values

#Loda the target data in variable y
y = dataset.iloc[:, -1].values
print(X)
print(y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [13]:
#Encoding categorical data
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [14]:

#Splitting the dataset into the Training set and Test set, 80% for the training and 20% for the testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
#Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



In [15]:

#Part 2 - Building the ANN
#Initializing the ANN
ann = tf.keras.models.Sequential()
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#Adding the output layer, adding one unit becuase its a binary classification task
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


In [16]:
#Part 3 - Training the ANN
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.8004 - loss: 0.5089
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - accuracy: 0.7892 - loss: 0.4648
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - accuracy: 0.7876 - loss: 0.4461
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.8033 - loss: 0.4412
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - accuracy: 0.8150 - loss: 0.4287
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - accuracy: 0.8159 - loss: 0.4290
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.8248 - loss: 0.4213
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.8293 - loss: 0.4142
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.8210 - loss: 0.4239
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - accuracy: 0.8280 - loss: 0.4134
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.8317 - loss: 0.4037
Epoch 12/100
250/25

In [19]:
#Part 4 - Making the predictions and evaluating the model
#Predicting the result of a single observation
#predict if the customer with the following informations will leave the bank:
"""
Use this ANN model to predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer?
Solution:
"""

#Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

"""
Therefore, our ANN model predicts that this customer stays in the bank!
Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method
always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D
array.
Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three
columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the
matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy
variables are always created in the first columns.
"""


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[0.06454208]]


'\nTherefore, our ANN model predicts that this customer stays in the bank!\nImportant note 1: Notice that the values of the features were all input in a double pair of square brackets. That\'s because the "predict" method\nalways expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D\narray.\nImportant note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three\ncolumns. That\'s because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the\nmatrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy\nvariables are always created in the first columns.\n'

In [18]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc = accuracy_score(y_test, y_pred)
print('Accuracy=', acc)

[[1538   57]
 [ 254  151]]
Accuracy= 0.8445
